from typing import List

class Point2D:
    def __init__(self, x: float = 0, y: float = 0): ...
    x: float
    y: float


class Py2DRenderer:
    def __init__(self) -> None: ...

    def set_primitives(self, shapes: List[List[Point2D]], color: int) -> None: ...
    def set_world_zoom_x(self, zoom: float) -> None: ...
    def set_world_zoom_y(self, zoom: float) -> None: ...
    def set_world_pan(self, x:float, y:float) -> None: ...
    def set_world_rotation(self, rotation: float) -> None: ...
    def set_world_space(self, enabled: bool) -> None: ...
    
    def set_screen_offset(self, x: float, y: float) -> None: ...
    def set_screen_zoom_x(self, zoom: float) -> None: ...
    def set_screen_zoom_y(self, zoom: float) -> None: ...
    def set_screen_pan(self, x: float, y: float) -> None: ...
    def set_screen_rotation(self, rotation: float) -> None: ...

    def set_circular_mask(self, enabled: bool) -> None: ...
    def set_mask_radius(self, radius: float) -> None: ...
    def set_mask_center(self, x: float, y: float) -> None: ...

    def render(self) -> None: ...
