from typing import List

class EffectType:
    skill_id: int
    attribute_level: int
    effect_id: int
    agent_id: int
    duration: float
    timestamp: int
    time_elapsed: int
    time_remaining: int

    def __init__(self, skill_id: int, attribute_level: int, effect_id: int, agent_id: int, 
                 duration: float, timestamp: int, time_elapsed: int, time_remaining: int) -> None: ...

class BuffType:
    skill_id: int
    buff_id: int
    target_agent_id: int

    def __init__(self, skill_id: int, buff_id: int, target_agent_id: int) -> None: ...

class PyEffects:
    def __init__(self, agent_id: int) -> None: ...
    def GetEffects(self) -> List[EffectType]: ...
    def GetBuffs(self) -> List[BuffType]: ...
    def GetEffectCount(self) -> int: ...
    def GetBuffCount(self) -> int: ...
    def EffectExists(self, skill_id: int) -> bool: ...
    def BuffExists(self, skill_id: int) -> bool: ...
    def DropBuff(self, skill_id: int) -> None: ...
    @staticmethod
    def GetAlcoholLevel() -> int: ...
    @staticmethod
    def ApplyDrunkEffect(intensity: int, tint: int) -> None: ...
    
