from typing import List

class PyScanCodeKeystroke:
    def __init__(self) -> None:...
    def PressKey(self, virtualKeyCode: int) -> None:...
    def ReleaseKey(self, virtualKeyCode: int) -> None:...
    def PushKey(self, virtualKeyCode: int) -> None:...
    def PressKeyCombo(self, keys: List[int]) -> None:...
    def ReleaseKeyCombo(self, keys: List[int]) -> None:...
    def PushKeyCombo(self, keys: List[int]) -> None:...
