# PyMerchant.pyi - Auto-generated .pyi file for PyMerchant module

from typing import Any

# Class Merchant
class Merchant:
    def __init__(self) -> None: ...
    
    def buy_item(self, model_id: int, quantity: int, price: int) -> None: ...
    def sell_item(self, model_id: int, quantity: int, price: int) -> None: ...
    def request_quote(self, model_id: int, quantity: int) -> None: ...
    def get_quoted_value(self) -> int: ...
    def is_requesting_quote(self) -> bool: ...
    def is_transaction_complete(self) -> bool: ...
    def update(self) -> None: ...
