# PyMerchant.pyi - Auto-generated .pyi file for PyMerchant module

# PyMerchant.pyi - Type stub for PyMerchant (PyBind11 bindings)

from typing import List

class PyMerchant:
    def __init__(self) -> None: ...
    def trader_buy_item(self, item_id: int, cost: int) -> bool: ...
    def trader_sell_item(self, item_id: int, price: int) -> bool: ...
    def trader_request_quote(self, item_id: int) -> bool: ...
    def trader_request_sell_quote(self, item_id: int) -> bool: ...
    def merchant_buy_item(self, item_id: int, cost: int) -> bool: ...
    def merchant_sell_item(self, item_id: int, price: int) -> bool: ...
    def crafter_buy_item(self, item_id: int, cost: int, give_item_ids: List[int], give_item_quantities: List[int]) -> bool: ...
    def collector_buy_item(self, item_id: int, cost: int, give_item_ids: List[int], give_item_quantities: List[int]) -> bool: ...
    def get_trader_item_list(self) -> List[int]: ...
    def get_trader_item_list2(self) -> List[int]: ...
    def get_merchant_item_list(self) -> List[int]: ...
    def get_quoted_value(self) -> int: ...
    def get_quoted_item_id(self) -> int: ...
    def is_transaction_complete(self) -> bool: ...
    def update(self) -> None: ...
