# PyPlayer.pyi - Auto-generated .pyi file for PyPlayer module

from typing import Any, List, overload
from PyAgent import PyAgent

# Class PyPlayer
class PyPlayer:
    id: int
    agent: PyAgent
    target_id: int
    mouse_over_id: int
    observing_id: int
    account_name: str
    wins: int
    losses: int
    rating: int
    qualifier_points: int
    rank: int
    tournament_reward_points: int
    morale: int
    experience: int
    current_kurzick: int
    total_earned_kurzick: int
    max_kurzick: int
    current_luxon: int
    total_earned_luxon: int
    max_luxon: int
    current_imperial: int
    total_earned_imperial: int
    max_imperial: int
    current_balth: int
    total_earned_balth: int
    max_balth: int
    current_skill_points: int
    total_earned_skill_points: int

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def GetAgentArray(self) -> List[int]: ...
    def GetAllyArray(self) -> List[int]: ...
    def GetNeutralArray(self) -> List[int]: ...
    def GetEnemyArray(self) -> List[int]: ...
    def GetSpiritPetArray(self) -> List[int]: ...
    def GetMinionArray(self) -> List[int]: ...
    def GetNPCMinipetArray(self) -> List[int]: ...
    def GetItemArray(self) -> List[int]: ...
    def GetGadgetArray(self) -> List[int]: ...
    def GetChatHistory(self) -> List[str]: ...
    def RequestChatHistory(self) -> None: ...
    def IsChatHistoryReady(self) -> bool: ...
    def SendChatCommand(self, msg: str) -> None: ...
    def SendChat(self, channel: str, msg: str) -> None: ...
    def SendWhisper(self, name: str, msg: str) -> None: ...
    def ChangeTarget(self, target_id: int) -> bool: ...
    @overload
    def Move(self, x: float, y: float, zplane: int) -> bool: ...
    @overload
    def Move(self, x: float, y: float) -> bool: ...
    def InteractAgent(self, agent_id: int, call_target: bool) -> bool: ...
    def OpenLockedChest(self, use_key: bool) -> bool: ...
    def SendDialog(self, dialog_id: int) -> None: ...
    def SetActiveTitle(self, title_id: int) -> bool: ...
    def RemoveActiveTitle(self) -> bool: ...
    def DepositFaction(self, allegiance: int) -> bool: ...
    def GetActiveTitleId(self) -> int: ...

class PyTitle:
    title_id: int
    props: int
    current_points: int
    current_title_tier_index: int
    points_needed_current_rank: int
    next_title_tier_index: int
    points_needed_next_rank: int
    max_title_rank: int
    max_title_tier_index: int
    is_percentage_based: bool
    has_tiers: bool

    def __init__(self, title_id: int) -> None: ...
    def GetContext(self) -> None: ...