# PySkill.pyi - Auto-generated .pyi file for PySkill module

from typing import List
from PySkill import SkillID
# PySkillbar.pyi - Auto-generated .pyi file for PySkillbar module

# Class SkillbarSkill
class SkillbarSkill:
    id: SkillID
    adrenaline_a: int
    adrenaline_b: int
    recharge: int
    event: int
    get_recharge: int

    def __init__(self, id: SkillID, adrenaline_a: int = 0, adrenaline_b: int = 0, recharge: int = 0, event: int = 0) -> None: ...


# Class Skillbar
class Skillbar:
    agent_id: int
    disabled: int
    casting: int
    skills: List[SkillbarSkill]

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def GetSkill(self, slot: int) -> SkillbarSkill: ...
    def LoadSkillTemplate(self, skill_template: str) -> bool: ...
    def LoadHeroSkillTemplate(self, hero_index: int, skill_template: str) -> bool: ...
    def UseSkill(self, slot: int, target: int = 0) -> None: ...
    def UseSkillTargetless(self, slot: int) -> None: ...
    def HeroUseSkill(self, target_agent_id: int, skill_number: int, hero_idx: int) -> bool: ...
    def ChangeHeroSecondary(self, hero_index: int, profession: int) -> bool: ...
    def GetHeroSkillbar(self, hero_index: int) -> List[SkillbarSkill]: ...
    def GetHoveredSkill(self) -> int: ...
    def IsSkillUnlocked(self, skill_id: int) -> bool: ...
    def IsSkillLearnt(self, skill_id: int) -> bool: ...